### ISSUE TITLE
JDK 16: AssertionError: expected: 8, actual: -12

### ISSUE THREAD

**Issue by itsdax** [OpenHFT/SmoothieMap#11]
Dependency:
```
        <dependency>
            <groupId>io.timeandspace</groupId>
            <artifactId>smoothie-map</artifactId>
            <version>2.0.2</version>
        </dependency>
 ```
 
Code:
```
import io.timeandspace.smoothie.SmoothieMap;

public class Main {

    public static void main(String[] args) {
        SmoothieMap.newBuilder().build();
    }

}
```

Command:
```
/Users/me/Library/Java/JavaVirtualMachines/openjdk-16.0.1/Contents/Home/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Dfile.encoding=UTF-8 -classpath /Users/me/projects/HelloJava/target/classes:/Users/me/.m2/repository/io/timeandspace/smoothie-map/2.0.2/smoothie-map-2.0.2.jar:/Users/me/.m2/repository/io/timeandspace/jpsg-core/1.4/jpsg-core-1.4.jar:/Users/me/.m2/repository/org/checkerframework/checker-qual/2.11.1/checker-qual-2.11.1.jar Main
```

Error:
```
Exception in thread "main" java.lang.AssertionError: expected: 8, actual: -12
	at io.timeandspace.smoothie.Utils.verifyEqual(Utils.java:63)
	at io.timeandspace.smoothie.InterleavedSegments$FullCapacitySegment.<clinit>(InterleavedSegments.java:605)
	at io.timeandspace.smoothie.InterleavedSegments.allocateSegment(InterleavedSegments.java:2150)
	at io.timeandspace.smoothie.InterleavedSegments.allocateNewSegmentWithoutSettingBitSetAndSet(InterleavedSegments.java:2130)
	at io.timeandspace.smoothie.InterleavedSegments.createNewSegment(InterleavedSegments.java:2137)
	at io.timeandspace.smoothie.SmoothieMap.<clinit>(SmoothieMap.java:291)
	at Main.main(Main.java:6)
```

**Comment by mazhimazh** [comment]
I have this problem
